export const TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjc1ODAyMDYxLCJpYXQiOjE2NzA5NjM2NjEsImp0aSI6IjdkNzQ5MDUxMjZkNjQwZTdiMGNkOTNjMTFkMGUxZGY4IiwidXNlcl9pZCI6MjV9.UtYKamvCmV187J_pov0OYS6cIIDZSJY60gB2K3ncPS0";
export const BASE_URL = "https://c-gallery.polinashneider.space/api/v1/";
export const TIMEOUT = 2000;